import Head from 'next/head'
import Navbar from './components/navbar'
import { useState } from 'react'
import Slider from './components/slider'
import Logos from './components/logos'
import Comparison from './components/comparison'
import Arrivals from './components/arrivals'
import Footer from './components/footer'
import HomeMedia from './components/homeMedia'
import Review from './components/review'
import Brands from './components/brands'
import { useAmp } from 'next/amp'

export const config = { amp: 'hybrid' }


export default function Home() {
  
  const [sticky , setSticky] = useState(false)

  global.onscroll = ()=>{
    scrollY > 20 ? setSticky(true) : setSticky(false);
  }
  return (
    <div>
      <Head>
        <title>Teximco BD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
       {
        isAmp ?    <h1 className='underline'>ahad</h1>  :     <Navbar></Navbar>
    <Slider></Slider>
   <Logos></Logos>
   <Comparison></Comparison>
   <Arrivals></Arrivals>
   <HomeMedia></HomeMedia>
   <Review></Review>
  <Brands></Brands>
   <Footer></Footer>
      }
 
 
    </div>
  )
}
